[package]
name = "aoc2022"
version = "0.1.0"
authors = ["Jeff Davey <jeffdavey@submersion.com>"]
edition = "2021"


[dependencies]
input = { path = "input" }
color-eyre = "0.5.11"
clap = { version = "4.0.29", features = ["derive"]}
ahash = "0.8.2"

[workspace]
members = [
    "input",
]
